### PR TITLE
Moved developer related documentation to own file.

### PR DESCRIPTION
**Pull request by cklam2**
Developer instructions moved to developer.MD
In readme.MD added a reference to travis.ci build result.

### CODE REVIEW

**Comment by coyoteecd** [comment]
Use CONTRIBUTING.md instead of DEVELOPER.md, see other packages in github

**Comment by cklam2** [comment]
Renamed to CONTRIBUTING.md

**Comment by cklam2** [comment]
Just a note: are you sure it should be CONTRIBUTING.md? 

It seems that when you have this file and you do a pull request it will show you the content of that file; which normally only contains the guidelines for contributing. Have not seen such file yet with also developer instructions.

**Comment by coyoteecd** [comment]
@cklam2 you're right, I renamed it back and merged it

**Pull request merged**
